### ISSUE TITLE
Can't start the program after updating to 0.7.3

### ISSUE THREAD

**Issue by PeterL1n** [relayrides/pushy#330]
Hey fellows,
I just updated to 0.7.3 from 0.7.2 through Maven
But the program won't start anymore
```
Exception in thread "main" java.lang.NoSuchMethodError: io.netty.bootstrap.Bootstrap.config()Lio/netty/bootstrap/BootstrapConfig;
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:434)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:266)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:239)
...
```

I used alpn-agent by the way.
Does anyone meet the same problem?

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue. In the meantime, it sounds like you have an old version of Netty somewhere in a cache. Try clearing your caches and running `mvn clean`.

I'll close this issue for now, but please do find us on the mailing list if you need more help. Cheers!
